# SPDX-FileCopyrightText: © 2024 Matt Williams <matt.williams@bristol.ac.uk>
# SPDX-License-Identifier: MIT

name: Build release
run-name: Build release${{ inputs.version && format(' {0}', inputs.version) || '' }}${{ inputs.dryrun && format(' (dry run)') || '' }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: The new version, can be "patch", "minor", "major", a valid semver string or empty
        type: string
        default: ""
      dryrun:
        description: Only do the build but do not publish the release
        required: true
        type: boolean
        default: false

permissions: {}

jobs:
  check-inputs:
    name: Check inputs
    runs-on: ubuntu-latest
    steps:
      - name: Check release branch
        if: github.ref_name != 'master'
        run: |
          echo "::error::Release must be made on the master branch"
          exit 1
      - name: Check version is set for release
        if: inputs.version == '' && !inputs.dryrun
        run: |
          echo "::error::Version must be set if not performing a dry run"
          exit 1
      - name: Check version format
        shell: bash
        if: ${{ !contains(fromJSON('["major", "minor", "patch"]'), inputs.version) && !inputs.dryrun}}
        run: |
          if ! [[ '${{ inputs.version }}' =~ [[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+ ]]; then
            echo "::error::Verseion string must be a valid semver string"
            exit 1
          fi

  check:
    name: Check
    needs: check-inputs
    uses: ./.github/workflows/check.yml
    with:
      ref: "${{ github.sha }}"
    permissions:
      contents: read

  tag-release:
    name: Tag release
    if: ${{ ! inputs.dryrun }}
    needs: check
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      ref: "${{ steps.get_version.outputs.version }}"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}  # Use ref here since we must commit on a branch
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - name: Install cargo-edit tool
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-edit
      - name: Update version string
        run: |
          echo Version input is '${{ inputs.version }}'
          if [ '${{ contains(fromJSON('["major", "minor", "patch"]'), inputs.version) }}' = 'true' ]; then
            echo 'Setting based on update spec'
            cargo set-version --bump ${{ inputs.version }}
          elif [ -n '${{ inputs.version }}' ]; then
            echo 'Updating based on explicit version'
            cargo set-version ${{ inputs.version }}
          fi
          git add Cargo.toml
      - name: Save the version
        id: get_version
        run: echo version="$(cargo metadata --format-version 1 --no-deps | jq --raw-output '.packages[0].version')" >> "${GITHUB_OUTPUT}"
      - name: Tag release
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git commit -m "Release ${{ steps.get_version.outputs.version }}"
          git tag "${{ steps.get_version.outputs.version }}"
          git push --atomic --tags origin HEAD

  build-release:
    name: "Build release (${{ matrix.target }})"
    if: ${{ always() && (needs.tag-release.result == 'success' || needs.tag-release.result == 'skipped') }}
    needs: tag-release
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: "x86_64-unknown-linux-gnu"
            os: "ubuntu-latest"
            cross: false
            output: clifton
            asset-name: clifton-linux-x86_64
            compress-binary: true
          - target: "aarch64-unknown-linux-gnu"
            os: "ubuntu-latest"
            cross: true
            output: clifton
            asset-name: clifton-linux-aarch64
            compress-binary: true
          - target: "x86_64-pc-windows-gnu"
            os: "ubuntu-latest"
            cross: true
            output: clifton.exe
            asset-name: clifton-windows-x86_64
            compress-binary: true
          - target: "aarch64-apple-darwin"
            os: "macOS-latest"
            cross: false
            output: clifton
            asset-name: clifton-macos-aarch64
            compress-binary: false
          - target: "x86_64-apple-darwin"
            os: "macOS-latest"
            cross: true
            output: clifton
            asset-name: clifton-macos-x86_64
            compress-binary: false
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.tag-release.outputs.ref || github.sha }}
          fetch-tags: true
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - name: Install cross
        uses: taiki-e/install-action@cross
        if: matrix.cross
      - name: Build
        run: cargo build --target=${{ matrix.target }} --release
        if: ${{ ! matrix.cross }}
      - name: Build
        run: cross build --target=${{ matrix.target }} --release
        if: matrix.cross
      - name: Rename assets
        run: cp target/${{ matrix.target }}/release/${{ matrix.output }} ${{ matrix.asset-name }}
      - name: Compress output
        run: |
          upx_ver="4.2.4"
          wget "https://github.com/upx/upx/releases/download/v${upx_ver}/upx-${upx_ver}-amd64_linux.tar.xz"
          tar xvf "upx-${upx_ver}-amd64_linux.tar.xz"
          upx-${upx_ver}-amd64_linux/upx ${{ matrix.asset-name }}
        if: ${{ matrix.compress-binary }}
      - name: Store build artefacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset-name }}
          path: |
            ${{ matrix.asset-name }}

  make-release:
    name: Make release ${{ needs.tag-release.outputs.ref }}
    if: ${{ ! inputs.dryrun }}
    needs: build-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Fetch release artefacts
        uses: actions/download-artifact@v4
        with:
          pattern: clifton-*
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.tag-release.outputs.ref }}
          files: clifton-*
